export {Header1 , Navbar,Header2} from './Headers'
export {default as Carousel } from './Carousel'
export {default as SellerProducts } from './SellerProducts'
export {default as FeaturedProduct} from './FeaturedProduct'
export {Footer1 ,Footer2,Footer3} from './Footers'
export {default as Review} from './Review'